name: terraform-tflint
description: Run tflint tests against terraform environment

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  ssh_key:
    description: ssh key for checkout tf modules
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Installs SSH key
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ env.TERRAFORM_SSH_KEY }}

    - name: terraform init
      working-directory: ${{ inputs.path }}
      shell: bash
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.local
        terraform init -backend=false
        ls -la ~/
        ls -la
        pwd
        echo $GITHUB_WORKSPACE

    - name: Install TFLint
      uses: terraform-linters/setup-tflint@v1
      with:
        github_token: ${{ env.GITHUB_TOKEN }}

    # TFLint looks up .tflint.hcl according to the following priority:
    # Current directory (./.tflint.hcl)
    # Home directory (~/.tflint.hcl)
    - name: Init TFLint
      working-directory: ${{ inputs.path }}
      shell: bash
      run: tflint --init

    - name: Run TFLint
      working-directory: ${{ inputs.path }}
      shell: bash
      run: tflint
